---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - groups
  - users
  verbs:
  - impersonate
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - get
  - impersonate
- apiGroups:
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
  - patch
  - update
- apiGroups:
  - opmodel.dev
  resources:
  - moduleinstances
  - modulepackages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - opmodel.dev
  resources:
  - moduleinstances/finalizers
  - modulepackages/finalizers
  verbs:
  - update
- apiGroups:
  - opmodel.dev
  resources:
  - moduleinstances/status
  - modulepackages/status
  - platforms/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - opmodel.dev
  resources:
  - platforms
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - source.toolkit.fluxcd.io
  resources:
  - buckets
  - gitrepositories
  - ocirepositories
  verbs:
  - get
  - list
  - watch
