// Code generated by hack/operator-module/generate.sh from the roles in config/rbac/kustomization.yaml with cue import. DO NOT EDIT.
// Regenerate with 'task dev:manifests'; 'task operator-module:drift'
// fails when this file no longer matches config/.

package opm_operator

#rbacSource: {
	"manager-role": {
		apiVersion: "rbac.authorization.k8s.io/v1"
		kind:       "ClusterRole"
		metadata: name: "manager-role"
		rules: [{
			apiGroups: [""]
			resources: ["events"]
			verbs: [
				"create",
				"patch",
			]
		}, {
			apiGroups: [""]
			resources: ["serviceaccounts"]
			verbs: [
				"get",
				"impersonate",
				"list",
				"watch",
			]
		}, {
			apiGroups: ["events.k8s.io"]
			resources: ["events"]
			verbs: [
				"create",
				"patch",
				"update",
			]
		}, {
			apiGroups: ["opmodel.dev"]
			resources: [
				"moduleinstances",
				"modulepackages",
			]
			verbs: [
				"create",
				"delete",
				"get",
				"list",
				"patch",
				"update",
				"watch",
			]
		}, {
			apiGroups: ["opmodel.dev"]
			resources: [
				"moduleinstances/finalizers",
				"modulepackages/finalizers",
				"transformerregistrations/finalizers",
			]
			verbs: ["update"]
		}, {
			apiGroups: ["opmodel.dev"]
			resources: [
				"moduleinstances/status",
				"modulepackages/status",
				"platforms/status",
				"transformerregistrations/status",
			]
			verbs: [
				"get",
				"patch",
				"update",
			]
		}, {
			apiGroups: ["opmodel.dev"]
			resources: ["platforms"]
			verbs: [
				"get",
				"list",
				"watch",
			]
		}, {
			apiGroups: ["opmodel.dev"]
			resources: ["transformerregistrations"]
			verbs: [
				"get",
				"list",
				"patch",
				"update",
				"watch",
			]
		}, {
			apiGroups: ["source.toolkit.fluxcd.io"]
			resources: [
				"buckets",
				"gitrepositories",
				"ocirepositories",
			]
			verbs: [
				"get",
				"list",
				"watch",
			]
		}]
	}
}
#rbacSource: {
	"leader-election-role": {
		apiVersion: "rbac.authorization.k8s.io/v1"
		kind:       "Role"
		metadata: {
			labels: {
				"app.kubernetes.io/name":       "opm-operator"
				"app.kubernetes.io/managed-by": "kustomize"
			}
			name: "leader-election-role"
		}
		rules: [{
			apiGroups: [""]
			resources: ["configmaps"]
			verbs: [
				"get",
				"list",
				"watch",
				"create",
				"update",
				"patch",
				"delete",
			]
		}, {
			apiGroups: ["coordination.k8s.io"]
			resources: ["leases"]
			verbs: [
				"get",
				"list",
				"watch",
				"create",
				"update",
				"patch",
				"delete",
			]
		}, {
			apiGroups: [""]
			resources: ["events"]
			verbs: [
				"create",
				"patch",
			]
		}]
	}
}
#rbacSource: {
	"metrics-auth-role": {
		apiVersion: "rbac.authorization.k8s.io/v1"
		kind:       "ClusterRole"
		metadata: name: "metrics-auth-role"
		rules: [{
			apiGroups: ["authentication.k8s.io"]
			resources: ["tokenreviews"]
			verbs: ["create"]
		}, {
			apiGroups: ["authorization.k8s.io"]
			resources: ["subjectaccessreviews"]
			verbs: ["create"]
		}]
	}
}
#rbacSource: {
	"metrics-reader": {
		apiVersion: "rbac.authorization.k8s.io/v1"
		kind:       "ClusterRole"
		metadata: name: "metrics-reader"
		rules: [{
			nonResourceURLs: ["/metrics"]
			verbs: ["get"]
		}]
	}
}
#rbacSource: {
	"moduleinstance-admin-role": {
		apiVersion: "rbac.authorization.k8s.io/v1"
		kind:       "ClusterRole"
		metadata: {
			labels: {
				"app.kubernetes.io/name":       "opm-operator"
				"app.kubernetes.io/managed-by": "kustomize"
			}
			name: "moduleinstance-admin-role"
		}
		rules: [{
			apiGroups: ["opmodel.dev"]
			resources: ["moduleinstances"]
			verbs: ["*"]
		}, {
			apiGroups: ["opmodel.dev"]
			resources: ["moduleinstances/status"]
			verbs: ["get"]
		}]
	}
}
#rbacSource: {
	"moduleinstance-editor-role": {
		apiVersion: "rbac.authorization.k8s.io/v1"
		kind:       "ClusterRole"
		metadata: {
			labels: {
				"app.kubernetes.io/name":       "opm-operator"
				"app.kubernetes.io/managed-by": "kustomize"
			}
			name: "moduleinstance-editor-role"
		}
		rules: [{
			apiGroups: ["opmodel.dev"]
			resources: ["moduleinstances"]
			verbs: [
				"create",
				"delete",
				"get",
				"list",
				"patch",
				"update",
				"watch",
			]
		}, {
			apiGroups: ["opmodel.dev"]
			resources: ["moduleinstances/status"]
			verbs: ["get"]
		}]
	}
}
#rbacSource: {
	"moduleinstance-viewer-role": {
		apiVersion: "rbac.authorization.k8s.io/v1"
		kind:       "ClusterRole"
		metadata: {
			labels: {
				"app.kubernetes.io/name":       "opm-operator"
				"app.kubernetes.io/managed-by": "kustomize"
			}
			name: "moduleinstance-viewer-role"
		}
		rules: [{
			apiGroups: ["opmodel.dev"]
			resources: ["moduleinstances"]
			verbs: [
				"get",
				"list",
				"watch",
			]
		}, {
			apiGroups: ["opmodel.dev"]
			resources: ["moduleinstances/status"]
			verbs: ["get"]
		}]
	}
}
#rbacSource: {
	"platform-viewer-role": {
		apiVersion: "rbac.authorization.k8s.io/v1"
		kind:       "ClusterRole"
		metadata: {
			labels: {
				"app.kubernetes.io/name":       "opm-operator"
				"app.kubernetes.io/managed-by": "kustomize"
			}
			name: "platform-viewer-role"
		}
		rules: [{
			apiGroups: ["opmodel.dev"]
			resources: ["platforms"]
			verbs: [
				"get",
				"list",
				"watch",
			]
		}, {
			apiGroups: ["opmodel.dev"]
			resources: ["platforms/status"]
			verbs: ["get"]
		}]
	}
}
#rbacSource: {
	"modulepackage-viewer-role": {
		apiVersion: "rbac.authorization.k8s.io/v1"
		kind:       "ClusterRole"
		metadata: {
			labels: {
				"app.kubernetes.io/name":       "opm-operator"
				"app.kubernetes.io/managed-by": "kustomize"
			}
			name: "modulepackage-viewer-role"
		}
		rules: [{
			apiGroups: ["opmodel.dev"]
			resources: ["modulepackages"]
			verbs: [
				"get",
				"list",
				"watch",
			]
		}, {
			apiGroups: ["opmodel.dev"]
			resources: ["modulepackages/status"]
			verbs: ["get"]
		}]
	}
}
#rbacSource: {
	"transformerregistration-viewer-role": {
		apiVersion: "rbac.authorization.k8s.io/v1"
		kind:       "ClusterRole"
		metadata: {
			labels: {
				"app.kubernetes.io/name":       "opm-operator"
				"app.kubernetes.io/managed-by": "kustomize"
			}
			name: "transformerregistration-viewer-role"
		}
		rules: [{
			apiGroups: ["opmodel.dev"]
			resources: ["transformerregistrations"]
			verbs: [
				"get",
				"list",
				"watch",
			]
		}, {
			apiGroups: ["opmodel.dev"]
			resources: ["transformerregistrations/status"]
			verbs: ["get"]
		}]
	}
}
#rbacSource: {
	"transformerregistration-admin-role": {
		apiVersion: "rbac.authorization.k8s.io/v1"
		kind:       "ClusterRole"
		metadata: {
			labels: {
				"app.kubernetes.io/name":       "opm-operator"
				"app.kubernetes.io/managed-by": "kustomize"
			}
			name: "transformerregistration-admin-role"
		}
		rules: [{
			apiGroups: ["opmodel.dev"]
			resources: ["transformerregistrations"]
			verbs: [
				"create",
				"update",
				"patch",
				"delete",
			]
		}, {
			apiGroups: ["opmodel.dev"]
			resources: ["transformerregistrations/status"]
			verbs: ["get"]
		}]
	}
}
