apiVersion: v1
kind: ServiceAccount
metadata:
  name: hello-deploy
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hello-deploy
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
  - kind: ServiceAccount
    name: hello-deploy
    namespace: default
---
apiVersion: releases.opmodel.dev/v1alpha1
kind: Release
metadata:
  labels:
    app.kubernetes.io/name: opm-operator
    app.kubernetes.io/managed-by: kustomize
  name: release-sample
  namespace: default
spec:
  serviceAccountName: hello-deploy
  sourceRef:
    apiVersion: source.toolkit.fluxcd.io/v1
    kind: GitRepository
    name: releases
  path: releases/local/hello
  interval: 5m
  prune: true
