/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Command crdref generates the operator resource reference, the block between
// the marker comments in docs/site/reference/operator-resources.md, from the
// operator's own sources:
//
//   - config/crd/bases: one entry per CustomResourceDefinition, its summary,
//     names, printer columns, spec and status fields and every rule the API
//     server enforces from the schema;
//   - config/samples: the entry's example, from the kubebuilder sample named
//     <group>_<version>_<kind>.yaml when one exists;
//   - internal/controller: the controller that reconciles the kind.
//
// An entry states only what those sources show: a part with nothing to show
// is left out. With -check, crdref writes nothing and fails when the
// committed page differs from what it would generate.
package main

import (
	"bufio"
	"bytes"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"io"
	"os"
	"path/filepath"
	"regexp"
	"slices"
	"strconv"
	"strings"

	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	utilyaml "k8s.io/apimachinery/pkg/util/yaml"
	"sigs.k8s.io/yaml"
)

const (
	pageFile      = "docs/site/reference/operator-resources.md"
	crdDir        = "config/crd/bases"
	samplesDir    = "config/samples"
	controllerDir = "internal/controller"

	beginMarker = "<!-- BEGIN GENERATED by hack/crdref from config/crd/bases, config/samples and " +
		"internal/controller. Do not edit; run task dev:docs:reference. -->"
	endMarker = "<!-- END GENERATED by hack/crdref -->"

	enforcedByAPIServer = "API server"
	typeArray           = "array"
	yes                 = "Yes"
	no                  = "No"
)

func main() {
	root := flag.String("root", ".", "repository root")
	check := flag.Bool("check", false, "fail when the committed page is stale instead of writing it")
	flag.Parse()
	if err := run(*root, *check); err != nil {
		fmt.Fprintln(os.Stderr, "crdref:", err)
		os.Exit(1)
	}
}

func run(root string, check bool) error {
	block, err := generate(root)
	if err != nil {
		return err
	}
	path := filepath.Join(root, pageFile)
	current, err := os.ReadFile(path)
	if err != nil {
		return err
	}
	updated, err := splice(string(current), block)
	if err != nil {
		return fmt.Errorf("%s: %w", pageFile, err)
	}
	if updated == string(current) {
		return nil
	}
	if check {
		return fmt.Errorf("%s is stale: run task dev:docs:reference and commit the result", pageFile)
	}
	return os.WriteFile(path, []byte(updated), 0o644)
}

// splice replaces the lines strictly between the begin and end markers with
// block. Both markers must stand on their own lines, once each, in order.
func splice(page, block string) (string, error) {
	lines := strings.SplitAfter(page, "\n")
	begin, end := -1, -1
	for i, l := range lines {
		switch strings.TrimRight(l, "\r\n") {
		case beginMarker:
			if begin >= 0 {
				return "", errors.New("begin marker appears twice")
			}
			begin = i
		case endMarker:
			if end >= 0 {
				return "", errors.New("end marker appears twice")
			}
			end = i
		}
	}
	if begin < 0 || end < 0 || end < begin {
		return "", fmt.Errorf("want the marker lines %q and %q, in that order", beginMarker, endMarker)
	}
	var b strings.Builder
	for _, l := range lines[:begin+1] {
		b.WriteString(l)
	}
	b.WriteString("\n")
	b.WriteString(block)
	b.WriteString("\n")
	for _, l := range lines[end:] {
		b.WriteString(l)
	}
	return b.String(), nil
}

// generate renders one entry per CRD, ordered by kind.
func generate(root string) (string, error) {
	crds, err := loadCRDs(filepath.Join(root, crdDir))
	if err != nil {
		return "", err
	}
	controllers, err := loadControllers(filepath.Join(root, controllerDir))
	if err != nil {
		return "", err
	}
	var b strings.Builder
	for i, crd := range crds {
		example, err := loadSample(filepath.Join(root, samplesDir), crd)
		if err != nil {
			return "", err
		}
		if i > 0 {
			b.WriteString("\n")
		}
		if err := writeEntry(&b, crd, example, controllers[crd.Spec.Names.Kind]); err != nil {
			return "", fmt.Errorf("%s: %w", crd.Spec.Names.Kind, err)
		}
	}
	// Each part ends in a blank line; the block ends in exactly one newline,
	// and splice puts one blank line between it and each marker.
	block := strings.TrimRight(blankRuns.ReplaceAllString(b.String(), "\n\n"), "\n") + "\n"
	if err := lintBlock(block); err != nil {
		return "", err
	}
	return block, nil
}

func loadCRDs(dir string) ([]*apiextensionsv1.CustomResourceDefinition, error) {
	files, err := filepath.Glob(filepath.Join(dir, "*.yaml"))
	if err != nil {
		return nil, err
	}
	if len(files) == 0 {
		return nil, fmt.Errorf("no CRDs in %s", dir)
	}
	crds := make([]*apiextensionsv1.CustomResourceDefinition, 0, len(files))
	for _, f := range files {
		data, err := os.ReadFile(f)
		if err != nil {
			return nil, err
		}
		crd := &apiextensionsv1.CustomResourceDefinition{}
		if err := yaml.UnmarshalStrict(data, crd); err != nil {
			return nil, fmt.Errorf("%s: %w", f, err)
		}
		if len(crd.Spec.Versions) != 1 || crd.Spec.Versions[0].Schema == nil ||
			crd.Spec.Versions[0].Schema.OpenAPIV3Schema == nil {
			return nil, fmt.Errorf("%s: want exactly one version with a schema", f)
		}
		crds = append(crds, crd)
	}
	slices.SortFunc(crds, func(a, b *apiextensionsv1.CustomResourceDefinition) int {
		return strings.Compare(a.Spec.Names.Kind, b.Spec.Names.Kind)
	})
	return crds, nil
}

// kubebuilder's scaffold labels on every sample. They say how the sample was
// applied in this repository, not anything about the resource, so the
// example leaves them out.
var scaffoldLabels = map[string]string{
	"app.kubernetes.io/name":       "opm-operator",
	"app.kubernetes.io/managed-by": "kustomize",
}

// testRegistry is the fixture domain. A sample that names it is a dev or e2e
// fixture, not something a reader can apply, so it is never shown.
const testRegistry = "testing.opmodel.dev"

// loadSample returns the first document of the CRD's kind in the sample file
// kubebuilder names <group>_<version>_<kind>.yaml, re-encoded without comments
// and scaffold labels, or nil when there is none or when that document
// references the test registry. The crdvalidation integration test proves
// every sample validates against its CRD.
func loadSample(dir string, crd *apiextensionsv1.CustomResourceDefinition) ([]byte, error) {
	group, version, kind := crd.Spec.Group, crd.Spec.Versions[0].Name, crd.Spec.Names.Kind
	path := filepath.Join(dir, fmt.Sprintf("%s_%s_%s.yaml", group, version, strings.ToLower(kind)))
	data, err := os.ReadFile(path)
	if errors.Is(err, os.ErrNotExist) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	reader := utilyaml.NewYAMLReader(bufio.NewReader(bytes.NewReader(data)))
	for {
		doc, err := reader.Read()
		if errors.Is(err, io.EOF) {
			return nil, nil
		}
		if err != nil {
			return nil, fmt.Errorf("%s: %w", path, err)
		}
		var obj map[string]any
		if err := yaml.Unmarshal(doc, &obj); err != nil {
			return nil, fmt.Errorf("%s: %w", path, err)
		}
		if obj["apiVersion"] != group+"/"+version || obj["kind"] != kind {
			continue
		}
		if bytes.Contains(doc, []byte(testRegistry)) {
			return nil, nil
		}
		if meta, ok := obj["metadata"].(map[string]any); ok {
			if labels, ok := meta["labels"].(map[string]any); ok {
				for k, v := range scaffoldLabels {
					if labels[k] == v {
						delete(labels, k)
					}
				}
				if len(labels) == 0 {
					delete(meta, "labels")
				}
			}
		}
		return yaml.Marshal(obj)
	}
}

// loadControllers maps each kind to the name of the controller that
// reconciles it: a function in internal/controller whose builder chain holds
// exactly one For(&<pkg>.<Kind>{...}) and one Named("<name>").
func loadControllers(dir string) (map[string]string, error) {
	files, err := filepath.Glob(filepath.Join(dir, "*.go"))
	if err != nil {
		return nil, err
	}
	out := map[string]string{}
	fset := token.NewFileSet()
	for _, f := range files {
		if strings.HasSuffix(f, "_test.go") {
			continue
		}
		file, err := parser.ParseFile(fset, f, nil, parser.SkipObjectResolution)
		if err != nil {
			return nil, err
		}
		for _, decl := range file.Decls {
			fn, ok := decl.(*ast.FuncDecl)
			if !ok || fn.Body == nil {
				continue
			}
			kinds, names := builderCalls(fn.Body)
			if len(kinds) == 1 && len(names) == 1 {
				out[kinds[0]] = names[0]
			}
		}
	}
	return out, nil
}

func builderCalls(body *ast.BlockStmt) (kinds, names []string) {
	ast.Inspect(body, func(n ast.Node) bool {
		call, ok := n.(*ast.CallExpr)
		if !ok || len(call.Args) == 0 {
			return true
		}
		sel, ok := call.Fun.(*ast.SelectorExpr)
		if !ok {
			return true
		}
		switch sel.Sel.Name {
		case "For":
			if u, ok := call.Args[0].(*ast.UnaryExpr); ok && u.Op == token.AND {
				if lit, ok := u.X.(*ast.CompositeLit); ok {
					if typ, ok := lit.Type.(*ast.SelectorExpr); ok {
						kinds = append(kinds, typ.Sel.Name)
					}
				}
			}
		case "Named":
			if lit, ok := call.Args[0].(*ast.BasicLit); ok && lit.Kind == token.STRING {
				if s, err := strconv.Unquote(lit.Value); err == nil {
					names = append(names, s)
				}
			}
		}
		return true
	})
	return kinds, names
}

func writeEntry(b *strings.Builder, crd *apiextensionsv1.CustomResourceDefinition, example []byte,
	controller string) error {
	version := crd.Spec.Versions[0]
	schema := version.Schema.OpenAPIV3Schema
	summary, notes := splitSummary(schema.Description)

	fmt.Fprintf(b, "## %s\n\n", crd.Spec.Names.Kind)
	if summary != "" {
		b.WriteString(inline(summary, false) + "\n\n")
	}
	writeGlance(b, crd, version)

	c := &collector{}
	c.root(*schema)
	if spec, ok := schema.Properties["spec"]; ok {
		c.object("spec", spec, &c.spec)
	}
	if status, ok := schema.Properties["status"]; ok {
		c.object("status", status, &c.status)
	}
	if len(c.unsupported) > 0 {
		return fmt.Errorf("schema constructs the reference does not render: %s", strings.Join(c.unsupported, "; "))
	}
	writeFields(b, "Spec", c.spec)
	writeFields(b, "Status", c.status)

	if len(example) > 0 {
		b.WriteString("### Example\n\n```yaml\n")
		b.Write(example)
		b.WriteString("```\n\n")
	}
	if len(notes) > 0 {
		b.WriteString("### Notes\n\n")
		for _, p := range notes {
			b.WriteString(inline(p, false) + "\n\n")
		}
	}
	if controller != "" {
		fmt.Fprintf(b, "### Served by\n\nThe operator's `%s` controller watches every %s.\n\n",
			controller, crd.Spec.Names.Kind)
	}
	if len(c.rules) > 0 {
		b.WriteString("### Enforcement\n\n")
		b.WriteString("| Field | Rule | Enforced by |\n| --- | --- | --- |\n")
		for _, r := range c.rules {
			fmt.Fprintf(b, "| %s | %s | %s |\n", r.field, r.text, enforcedByAPIServer)
		}
		b.WriteString("\n")
	}
	return nil
}

func writeGlance(b *strings.Builder, crd *apiextensionsv1.CustomResourceDefinition,
	version apiextensionsv1.CustomResourceDefinitionVersion) {
	names := crd.Spec.Names
	b.WriteString("### At a glance\n\n| Property | Value |\n| --- | --- |\n")
	fmt.Fprintf(b, "| Group | `%s` |\n", crd.Spec.Group)
	fmt.Fprintf(b, "| Version | `%s` |\n", version.Name)
	fmt.Fprintf(b, "| Kind | `%s` |\n", names.Kind)
	fmt.Fprintf(b, "| Scope | %s |\n", crd.Spec.Scope)
	fmt.Fprintf(b, "| Resource | `%s` |\n", names.Plural)
	if len(names.ShortNames) > 0 {
		fmt.Fprintf(b, "| Short names | %s |\n", codeList(names.ShortNames))
	}
	if len(names.Categories) > 0 {
		fmt.Fprintf(b, "| Categories | %s |\n", codeList(names.Categories))
	}
	if sub := version.Subresources; sub != nil {
		var subs []string
		if sub.Status != nil {
			subs = append(subs, "status")
		}
		if sub.Scale != nil {
			subs = append(subs, "scale")
		}
		if len(subs) > 0 {
			fmt.Fprintf(b, "| Subresources | %s |\n", codeList(subs))
		}
	}
	b.WriteString("\n")

	if len(version.AdditionalPrinterColumns) == 0 {
		return
	}
	b.WriteString("The resource definition declares these `kubectl get` columns. " +
		"A column with a priority above 0 appears only with `-o wide`.\n\n")
	b.WriteString("| Column | Type | Value | Priority |\n| --- | --- | --- | --- |\n")
	for _, col := range version.AdditionalPrinterColumns {
		fmt.Fprintf(b, "| %s | %s | %s | %d |\n", inline(col.Name, true), col.Type,
			code(col.JSONPath, true), col.Priority)
	}
	b.WriteString("\n")
}

type field struct {
	path, typ, def, desc string
	required             bool
}

type rule struct {
	field, text string
}

type collector struct {
	spec, status []field
	rules        []rule
	unsupported  []string
}

// refuse records every schema construct the entry has no way to show, so
// generation fails instead of dropping a rule or a shape silently.
func (c *collector) refuse(path string, s apiextensionsv1.JSONSchemaProps) {
	if path == "" {
		path = "the object"
	}
	for name, present := range map[string]bool{
		"allOf": len(s.AllOf) > 0, "oneOf": len(s.OneOf) > 0, "anyOf": len(s.AnyOf) > 0,
		"not": s.Not != nil, "nullable": s.Nullable,
	} {
		if present {
			c.unsupported = append(c.unsupported, path+": "+name)
		}
	}
	slices.Sort(c.unsupported)
}

func (c *collector) rule(path, text string) {
	f := "the object"
	if path != "" {
		f = code(path, true)
	}
	c.rules = append(c.rules, rule{field: f, text: text})
}

// root records the rules declared on the object itself: its required
// top-level fields and its CEL validations.
func (c *collector) root(s apiextensionsv1.JSONSchemaProps) {
	c.refuse("", s)
	c.validations("", s)
	for _, name := range sorted(s.Required) {
		c.rule(name, "Required")
	}
}

// object records a row and the rules for every property of s, recursing
// into nested objects, array items and map values.
func (c *collector) object(prefix string, s apiextensionsv1.JSONSchemaProps, rows *[]field) {
	required := map[string]bool{}
	for _, r := range s.Required {
		required[r] = true
	}
	for _, name := range sortedKeys(s.Properties) {
		c.field(prefix+"."+name, s.Properties[name], required[name], rows)
	}
}

func (c *collector) field(path string, s apiextensionsv1.JSONSchemaProps, required bool, rows *[]field) {
	f := field{path: path, typ: typeOf(s), required: required, desc: flatten(s.Description)}
	if s.Default != nil {
		f.def = string(s.Default.Raw)
	}
	*rows = append(*rows, f)
	if required {
		c.rule(path, "Required")
	}
	if isConditions(s) {
		// The standard metav1.Condition list: its own rules are Kubernetes',
		// and the operator conditions page documents the types and reasons.
		return
	}
	c.constraints(path, s)
	c.descend(path, s, rows)
}

func (c *collector) descend(path string, s apiextensionsv1.JSONSchemaProps, rows *[]field) {
	switch {
	case len(s.Properties) > 0:
		c.object(path, s, rows)
	case s.Items != nil && s.Items.Schema != nil:
		c.constraints(path+"[]", *s.Items.Schema)
		c.descend(path+"[]", *s.Items.Schema, rows)
	case s.AdditionalProperties != nil && s.AdditionalProperties.Schema != nil:
		c.constraints(path+".<key>", *s.AdditionalProperties.Schema)
		c.descend(path+".<key>", *s.AdditionalProperties.Schema, rows)
	}
}

// constraints records every rule the API server enforces from the schema of
// one value, apart from required, which the parent declares.
func (c *collector) constraints(path string, s apiextensionsv1.JSONSchemaProps) {
	c.refuse(path, s)
	if s.MinLength != nil {
		if *s.MinLength == 1 {
			c.rule(path, "Must not be empty")
		} else {
			c.rule(path, fmt.Sprintf("At least %d characters", *s.MinLength))
		}
	}
	if s.MaxLength != nil {
		c.rule(path, fmt.Sprintf("At most %d characters", *s.MaxLength))
	}
	if s.Pattern != "" {
		c.rule(path, "Matches the pattern "+code(s.Pattern, true))
	}
	if len(s.Enum) > 0 {
		values := make([]string, 0, len(s.Enum))
		for _, e := range s.Enum {
			values = append(values, enumValue(e.Raw))
		}
		c.rule(path, "One of "+codeList(values))
	}
	if s.Minimum != nil {
		c.rule(path, bound("At least", "Greater than", *s.Minimum, s.ExclusiveMinimum))
	}
	if s.Maximum != nil {
		c.rule(path, bound("At most", "Less than", *s.Maximum, s.ExclusiveMaximum))
	}
	if s.MinItems != nil {
		c.rule(path, fmt.Sprintf("At least %d items", *s.MinItems))
	}
	if s.MaxItems != nil {
		c.rule(path, fmt.Sprintf("At most %d items", *s.MaxItems))
	}
	if s.MinProperties != nil {
		c.rule(path, fmt.Sprintf("At least %d entries", *s.MinProperties))
	}
	if s.MaxProperties != nil {
		c.rule(path, fmt.Sprintf("At most %d entries", *s.MaxProperties))
	}
	if s.UniqueItems || (s.XListType != nil && *s.XListType == "set") {
		c.rule(path, "No duplicate items")
	}
	if s.XListType != nil && *s.XListType == "map" && len(s.XListMapKeys) > 0 {
		c.rule(path, "At most one item per "+codeList(s.XListMapKeys))
	}
	c.validations(path, s)
}

func (c *collector) validations(path string, s apiextensionsv1.JSONSchemaProps) {
	for _, v := range s.XValidations {
		text := "CEL rule " + code(v.Rule, true)
		if v.Message != "" {
			text += "; refused with: " + inline(v.Message, true)
		}
		c.rule(path, text)
	}
}

func writeFields(b *strings.Builder, title string, rows []field) {
	if len(rows) == 0 {
		return
	}
	withDefault := slices.ContainsFunc(rows, func(f field) bool { return f.def != "" })
	fmt.Fprintf(b, "### %s\n\n", title)
	if withDefault {
		b.WriteString("| Field | Type | Required | Default | Description |\n| --- | --- | --- | --- | --- |\n")
	} else {
		b.WriteString("| Field | Type | Required | Description |\n| --- | --- | --- | --- |\n")
	}
	for _, f := range rows {
		req := no
		if f.required {
			req = yes
		}
		if withDefault {
			def := ""
			if f.def != "" {
				def = code(f.def, true)
			}
			fmt.Fprintf(b, "| %s | %s | %s | %s | %s |\n", code(f.path, true), code(f.typ, true), req, def,
				inline(f.desc, true))
		} else {
			fmt.Fprintf(b, "| %s | %s | %s | %s |\n", code(f.path, true), code(f.typ, true), req,
				inline(f.desc, true))
		}
	}
	b.WriteString("\n")
}

func typeOf(s apiextensionsv1.JSONSchemaProps) string {
	switch {
	case isConditions(s):
		return "[]Condition"
	case s.XIntOrString:
		return "integer or string"
	case s.Type == typeArray:
		if s.Items != nil && s.Items.Schema != nil {
			return "[]" + typeOf(*s.Items.Schema)
		}
		return typeArray
	case s.Type == "object" && s.AdditionalProperties != nil && s.AdditionalProperties.Schema != nil:
		return "map[string]" + typeOf(*s.AdditionalProperties.Schema)
	case s.Type == "object" && len(s.Properties) == 0 &&
		s.XPreserveUnknownFields != nil && *s.XPreserveUnknownFields:
		return "free-form object"
	case s.Type == "string" && s.Format == "date-time":
		return "string (date-time)"
	case s.Type != "":
		return s.Type
	case s.XPreserveUnknownFields != nil && *s.XPreserveUnknownFields:
		return "free-form object"
	}
	return "any"
}

// isConditions reports whether s is the standard metav1.Condition list,
// keyed by type.
func isConditions(s apiextensionsv1.JSONSchemaProps) bool {
	if s.Type != typeArray || s.Items == nil || s.Items.Schema == nil ||
		!slices.Equal(s.XListMapKeys, []string{"type"}) {
		return false
	}
	item := s.Items.Schema
	for _, p := range []string{"lastTransitionTime", "message", "reason", "status", "type"} {
		if _, ok := item.Properties[p]; !ok || !slices.Contains(item.Required, p) {
			return false
		}
	}
	return true
}

func bound(inclusive, exclusive string, v float64, isExclusive bool) string {
	word := inclusive
	if isExclusive {
		word = exclusive
	}
	return word + " " + strconv.FormatFloat(v, 'f', -1, 64)
}

func enumValue(raw []byte) string {
	var s string
	if err := json.Unmarshal(raw, &s); err == nil {
		return s
	}
	return string(raw)
}

var (
	paragraphBreak = regexp.MustCompile(`\n[ \t]*\n`)
	blankRuns      = regexp.MustCompile(`\n{3,}`)
)

// paragraphs splits a doc comment, as controller-gen copied it into the
// schema, into paragraphs with their line breaks and runs of space folded.
func paragraphs(s string) []string {
	var out []string
	for _, p := range paragraphBreak.Split(strings.TrimSpace(s), -1) {
		if p = strings.Join(strings.Fields(p), " "); p != "" {
			out = append(out, p)
		}
	}
	return out
}

// flatten folds a doc comment onto one line, for a table cell.
func flatten(s string) string {
	return strings.Join(paragraphs(s), " ")
}

// splitSummary returns the first sentence of a doc comment and the rest of
// it, paragraph by paragraph.
func splitSummary(desc string) (string, []string) {
	ps := paragraphs(desc)
	if len(ps) == 0 {
		return "", nil
	}
	summary, rest := firstSentence(ps[0])
	var notes []string
	if rest != "" {
		notes = append(notes, rest)
	}
	return summary, append(notes, ps[1:]...)
}

func firstSentence(p string) (string, string) {
	for i := 0; i < len(p); i++ {
		if p[i] != '.' || (i+1 < len(p) && p[i+1] != ' ') {
			continue
		}
		if strings.HasSuffix(p[:i+1], "e.g.") || strings.HasSuffix(p[:i+1], "i.e.") {
			continue
		}
		return p[:i+1], strings.TrimSpace(p[i+1:])
	}
	return p, ""
}

func code(s string, inTable bool) string {
	if inTable {
		s = strings.ReplaceAll(s, "|", `\|`)
	}
	fence := "`"
	for strings.Contains(s, fence) {
		fence += "`"
	}
	if strings.HasPrefix(s, "`") || strings.HasSuffix(s, "`") {
		return fence + " " + s + " " + fence
	}
	return fence + s + fence
}

func codeList(items []string) string {
	out := make([]string, 0, len(items))
	for _, i := range items {
		out = append(out, code(i, true))
	}
	return strings.Join(out, ", ")
}

// markdownEscaper escapes the characters that would otherwise start
// emphasis, a link, raw HTML or a table cell. The site renders raw HTML, so
// an unescaped <name> in a doc comment would become a tag.
var markdownEscaper = strings.NewReplacer(
	`\`, `\\`, "*", `\*`, "_", `\_`, "[", `\[`, "]", `\]`, "<", `\<`, ">", `\>`,
	"~", `\~`, "|", `\|`, "#", `\#`,
)

// citation matches an enhancement decision reference such as 0015:D3,
// 0015:D3/D16 or 0011:D9:R2.
var citation = regexp.MustCompile(`\b(\d{4}):D\d+(?::R\d+(?:/R\d+)*)?(?:/D\d+(?::R\d+(?:/R\d+)*)?)*`)

// inline renders doc-comment text as Markdown inline content: backtick
// spans stay code, everything else is escaped, and an enhancement decision
// reference links to that enhancement's decisions.
func inline(s string, inTable bool) string {
	parts := strings.Split(s, "`")
	if len(parts)%2 == 0 {
		// An unpaired backtick: no code spans, escape it too.
		return strings.ReplaceAll(prose(s), "`", "\\`")
	}
	var b strings.Builder
	for i, part := range parts {
		if i%2 == 1 {
			b.WriteString(code(part, inTable))
			continue
		}
		b.WriteString(prose(part))
	}
	return b.String()
}

func prose(s string) string {
	return citation.ReplaceAllString(markdownEscaper.Replace(s), "[$0](/enhancements/$1/decisions/)")
}

// shortcode, rawLink and image are what the site's page lint rejects and
// what the site engine would act on in text taken from a doc comment.
var (
	shortcode = regexp.MustCompile(`\{\{[<%]`)
	rawLink   = regexp.MustCompile(`(?i)(href|src)[ \t]*=`)
	image     = regexp.MustCompile(`!\[`)
)

func lintBlock(block string) error {
	for n, l := range strings.Split(block, "\n") {
		if shortcode.MatchString(l) || rawLink.MatchString(l) || image.MatchString(l) {
			return fmt.Errorf("generated line %d would break the page dialect: %s", n+1, l)
		}
	}
	return nil
}

func sortedKeys(m map[string]apiextensionsv1.JSONSchemaProps) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	slices.Sort(keys)
	return keys
}

func sorted(s []string) []string {
	out := slices.Clone(s)
	slices.Sort(out)
	return out
}
