#!/usr/bin/env bash
# Generate the operator module's CRD and RBAC data from the controller's
# kustomize tree with `cue import` (never @embed: the kernel loads only the
# .cue files of a module tree).
#
#   hack/operator-module/generate.sh                    # config/ -> modules/opm_operator/
#   SRC=/path/to/config hack/operator-module/generate.sh # another config/ tree
#   OUT=/tmp/x hack/operator-module/generate.sh          # write elsewhere (the drift check)
#
# Writes:
#   $OUT/zz_generated_crds.cue  #crdSource:  <CRD name>: <CRD as imported>,
#                               from $SRC/crd/bases/*.yaml in sorted order
#   $OUT/zz_generated_rbac.cue  #rbacSource: <unprefixed role name>: <role as imported>,
#                               from every file in the resources of
#                               $SRC/rbac/kustomization.yaml whose kind is
#                               Role or ClusterRole, in the listed order
set -euo pipefail

ROOT=$(cd "$(dirname "$0")/../.." && pwd)
SRC=${SRC:-$ROOT/config}
OUT=${OUT:-$ROOT/modules/opm_operator}
PKG=opm_operator

[ -d "$SRC/crd/bases" ] || { echo "$0: no CRD directory $SRC/crd/bases" >&2; exit 1; }
[ -f "$SRC/rbac/kustomization.yaml" ] || { echo "$0: no $SRC/rbac/kustomization.yaml" >&2; exit 1; }

tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT

# One multi-document stream per kind of data, in a stable order. Comment lines
# are prose and would become doc comments on the first imported field.
mapfile -t crds < <(find "$SRC/crd/bases" -maxdepth 1 -name '*.yaml' | LC_ALL=C sort)
[ "${#crds[@]}" -gt 0 ] || { echo "$0: no CRDs in $SRC/crd/bases" >&2; exit 1; }
for f in "${crds[@]}"; do
	printf -- '---\n' >>"$tmp/crds.yaml"
	grep -v '^#' "$f" >>"$tmp/crds.yaml"
done

# The role files are the kustomization's own resources list, filtered by kind,
# so a role added there lands here with no list to update by hand.
mapfile -t resources < <(cue export --out yaml -e resources "$SRC/rbac/kustomization.yaml" | sed -n 's/^- //p')
roles=0
for r in "${resources[@]}"; do
	f="$SRC/rbac/$r"
	[ -f "$f" ] || { echo "$0: $SRC/rbac/kustomization.yaml lists $r, which does not exist" >&2; exit 1; }
	kind=$(cue export --out text -e kind "$f")
	case "$kind" in
	Role | ClusterRole) ;;
	*) continue ;;
	esac
	printf -- '---\n' >>"$tmp/rbac.yaml"
	grep -v '^#' "$f" >>"$tmp/rbac.yaml"
	roles=$((roles + 1))
done
[ "$roles" -gt 0 ] || { echo "$0: no Role or ClusterRole in $SRC/rbac/kustomization.yaml" >&2; exit 1; }

cue import -f -p "$PKG" -l '#crdSource:' -l 'metadata.name' -o "$tmp/crds.cue" "$tmp/crds.yaml"
cue import -f -p "$PKG" -l '#rbacSource:' -l 'metadata.name' -o "$tmp/rbac.cue" "$tmp/rbac.yaml"

# The header never names the input tree, so a file generated from SRC= is
# byte-comparable with the committed one.
header() {
	cat <<HDR
// Code generated by hack/operator-module/generate.sh from $1 with cue import. DO NOT EDIT.
// Regenerate with 'task dev:manifests operator-module:generate'; 'task operator-module:drift'
// fails when this file no longer matches config/.

HDR
}

mkdir -p "$OUT"
{ header "config/crd/bases"; cat "$tmp/crds.cue"; } >"$OUT/zz_generated_crds.cue"
{ header "the roles in config/rbac/kustomization.yaml"; cat "$tmp/rbac.cue"; } >"$OUT/zz_generated_rbac.cue"
cue fmt "$OUT/zz_generated_crds.cue" "$OUT/zz_generated_rbac.cue"
echo "wrote $OUT/zz_generated_crds.cue ($((${#crds[@]})) CRDs) and $OUT/zz_generated_rbac.cue ($roles roles)"
